
spring:
  jpa:
    show-sql: false

  datasource:
    url: jdbc:postgresql://postgres:5432/insurance_prod

logging:
  level:
    com.example.insurance: INFO

springdoc:
  swagger-ui:
    enabled: false